### ISSUE TITLE
Inverted Y coordinates

### ISSUE THREAD

**Issue by HadyGalal** [blazium-engine/blazium#113]
### Tested versions

-Reproducable in: 4.3.dev

### System information

Godot v4.3.stable.mono (bc7131249) - Windows 10.0.22621 - Vulkan (Forward+) - dedicated NVIDIA GeForce RTX 3060 Laptop GPU (NVIDIA; 32.0.15.6109) - AMD Ryzen 7 6800HS with Radeon Graphics (16 Threads)

### Issue description

i built the mono build for the engine and when testing it, i noticed the the Y coordinates are inverted, going downwards is the positive direction and going upwards is the negative direction, this isn't a serious issue but it's something I felt I should report

### Steps to reproduce

Open the editor, create a Node2D, and move it up and down and check the positions

### Minimal reproduction project (MRP)

[blazium-mono-test.zip](https://github.com/user-attachments/files/17590589/blazium-mono-test.zip)

**Comment by Norrox** [comment]
This happens in the non mono version, and same in godot 4.3 mono

**Comment by jss2a98aj** [comment]
This is unfortunately standard behavior for Godot.

**Comment by Bioblaze** [comment]
This would break every single game project that is currently in use with the engine. We can't agree to implement this im sorry. Maybe we can do it on a Major Compat. Change next year in 2026
