### ISSUE TITLE
Free WebRTC Signaling Server for games

### ISSUE THREAD

**Issue by Ughuuu** [blazium-engine/blazium#119]
Would be nice to offer a free webrtc server. In case someone makes a game that is peer to peer, he still would need to host his signaling server.  Would be nice to have something free to use. Example signaling server in nodejs https://github.com/Faless/gd-webrtc-signalling/blob/master/server_node/server.js

**Comment by Bioblaze** [comment]
https://github.com/blazium-engine/blazium-signal
Does this work out?

I'm going to try and replicate it 1-1, still missing some bits, and the tests need work. 

But its a start.

**Comment by Ughuuu** [comment]
Looks good I think, needs a documentation to document the protocol, as you said tests to make sure flows work, and to deploy it somewhere so users can test it. We should figure out some statistics too, eg. how many users can use this service.
