### ISSUE TITLE
Rebranding in Engine

### ISSUE THREAD

**Issue by Starkium** [blazium-engine/blazium#36]
![Image](https://github.com/user-attachments/assets/33d096c5-4fab-4d7a-99bc-9ef48aaa6664)
![Image](https://github.com/user-attachments/assets/63642e55-fbb0-401c-9774-6c4e4dc2e61a)
![Image](https://github.com/user-attachments/assets/2dc9d5ac-be8a-4515-9ed6-6e3c2f7dc7bd)
![Image](https://github.com/user-attachments/assets/450fdd0c-cf78-4278-858d-b6785f988f0d)
![Image](https://github.com/user-attachments/assets/eb1f631c-4e15-4436-90e3-0bdf9b674715)
![image](https://github.com/user-attachments/assets/36e5a174-bd89-403b-95a7-c14f45c8e574)
![image](https://github.com/user-attachments/assets/f270f076-8bb7-4e56-b500-8233bf94e5ae)
![image](https://github.com/user-attachments/assets/edbe1dc5-7ba2-444e-9800-1f44f79c6232)

**Comment by jss2a98aj** [comment]
#37 addresses the help dropdown.

**Comment by Captain-Wet-Beard** [comment]
#38 probably addresses some of that

**Comment by Norrox** [comment]
https://github.com/blazium-engine/blazium/pull/42
