### ISSUE TITLE
Implement support for updating plugins inside the editor [old proposal from 2023]

### ISSUE THREAD

**Issue by Ughuuu** [blazium-engine/blazium#49]
Based off https://github.com/godotengine/godot-proposals/issues/8451

1. Check for updates.
2. Check local files against server base files checksum.
3. Ask user to update plugin IF there are local changes (replace ALL, replace NONE)
4. Download files
5. Unzip files
6. Release DLL handles (windows only)
6a. If Addon Crash or Error on Unload, Ask user to Restart with that plugin Disabled.
7. Delete old files
9. Copy new files

There should be an update and update all button for addons. There should also be a message saying update available. Possibly we should also show changelog:

![image](https://github.com/user-attachments/assets/211c0e03-329b-4f32-9f01-2654788dfda0)

Also, since we are on this, the Plugins tab should be renamed to Addons tab, since that's how it is called in other screens.

<img width="1135" alt="Screenshot 2024-10-17 at 23 18 53" src="https://github.com/user-attachments/assets/66508c17-4d50-4852-bf01-ef479a6c408c">

**Comment by Bioblaze** [comment]
Godot is implementing that it was just announced closing this.
