### ISSUE TITLE
The default project icon has ugly corners

### ISSUE THREAD

**Issue by Norrox** [blazium-engine/blazium#55]
### Tested versions

-

### System information

-

### Issue description

The SVG looks fine, i think it's the editor doing some funny stuff to it.
![Screenshot 2024-10-17 231157](https://github.com/user-attachments/assets/9afebd03-63c4-4d60-98a2-613bca1ab258)

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by sshiiden** [comment]
Seems to be a problem with Godot.

Blazium left, Godot Right.
![image](https://github.com/user-attachments/assets/45e3b4e7-cecf-44ba-813e-5196d7d805a4)

**Comment by Norrox** [comment]
https://github.com/blazium-engine/blazium/pull/85 closed this issue
