### ISSUE TITLE
Default view on scenes when importing to blazium 4.3 default to wireframe

### ISSUE THREAD

**Issue by Norrox** [blazium-engine/blazium#74]
### Tested versions

v4.3.stable.custom_build [ce7311f34]

### System information

Windows 11, Ryzen 9 7900X, 7900XTX, 64G Ram

### Issue description

Other need to check this, or if this was something fishy with my project...
Majority of my scenes defaulted to wireframe when imporing from godot to blazium
![image](https://github.com/user-attachments/assets/6070503b-927f-459a-87f1-88c8e61ad61b)

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by Starkium** [comment]
is this still an issue?
