### ISSUE TITLE
Terrible memory leak when importing a large git cloned repository

### ISSUE THREAD

**Issue by Norrox** [blazium-engine/blazium#90]
### Tested versions

-

### System information

-

### Issue description

See https://github.com/godotengine/godot/issues/97610

Anyone here have any ideas what can cause this,
I will do some investigation myself but have limited knowledge so any assistance is appreciated.

### Steps to reproduce

-

### Minimal reproduction project (MRP)

-

**Comment by Norrox** [comment]
A thread on Reddit on the issue as well 
https://www.reddit.com/r/godot/s/SLW8biIRor

**Comment by cryoboltinteractive** [comment]
Thank you for this, but the issue seems resolved in master branch of Godot Engine!

**Comment by Norrox** [comment]
> Thank you for this, but the issue seems resolved in master branch of Godot Engine!

yeah i see now!
here it is, https://github.com/godotengine/godot/pull/98584
is this something we can cherry pick for 4.3?

**Comment by jss2a98aj** [comment]
Yeah, that should be easy to cherry pick

**Comment by Starkium** [comment]
is this already merged in?

**Comment by jss2a98aj** [comment]
> is this already merged in?

Will be with #122
