### ISSUE TITLE
Automatically enable newly installed addons

### ISSUE THREAD

**Issue by Ughuuu** [blazium-engine/blazium#91]
After installing an addon in the editor, it's not enabled. Give an option to enable it just as you install it.

![](https://user-images.githubusercontent.com/28286961/71269313-55608980-234f-11ea-9c21-1b6ad2168e12.png)

PRs:

https://github.com/godotengine/godot/pull/94481
https://github.com/godotengine/godot/pull/35234

Proposal:

https://github.com/godotengine/godot-proposals/issues/324

**Comment by Norrox** [comment]
Do we need this pr before we merge this feature?
https://github.com/godotengine/godot/issues/36713

**Comment by Bioblaze** [comment]
This is a Security concern Ping me about it directly.
