### ISSUE TITLE
File System / Level Load Seems Slow

### ISSUE THREAD

**Issue by Starkium** [blazium-engine/blazium#93]
### Tested versions

4.3 Dev

### System information

N/A

### Issue description

I've noticed that, compared to other engines (Unreal, Unity, Etc.), switching between mostly empty levels is slow. Likely same with the rest of the file system.

### Steps to reproduce

Swap between very minimal levels in packaged project or in play. 

### Minimal reproduction project (MRP)

N/A

**Comment by Saul2022** [comment]
It’s prob due to the loading screen that happens between switching scenes, though does not look to be file system fault as now opening projects in 4.4 is way faster.

**Comment by jss2a98aj** [comment]
File access and level loading should be faster when using a build made with the production flag on
