### ISSUE TITLE
Property not found: xr/openxr/enabled.editor

### ISSUE THREAD

**Issue by Norrox** [blazium-engine/blazium#96]
### Tested versions

Blazium Engine v4.3.stable.custom_build.3d368f603 ( blazium-dev )

### System information

Windows 11

### Issue description

This is probably nothing, but a warning showed up in the console when i started the engine after compiled it just now.

![image](https://github.com/user-attachments/assets/11cb3310-da9c-4ad6-abcd-7feaf998a409)

### Steps to reproduce

Just start the engine

### Minimal reproduction project (MRP)

-

**Comment by sshiiden** [comment]
It seems like it wasn't defined; [this PR](https://github.com/godotengine/godot/pull/96780) fixes the issue.

**Comment by Starkium** [comment]
seems we already pulled those changes in. I'm going to close this ticket for now
